# Generated by Django 5.0.6 on 2024-07-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_order_customer_alter_orderitems_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddressmodel',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
    ]
